variables:
  GIT_STRATEGY: none

stages:
  - build

.build:
  variables:
    GIT_STRATEGY: fetch
  stage: build
  interruptible: true
  script:
    - cmake --preset clang -DUSE_CPM=OFF
    - cmake --build --preset clang --config Debug
    - cmake --build --preset clang --config Release
    - cd build
    - ctest -V -C Debug
    - ctest -V -C Release

build:windows:
  extends: [.build]
  tags:
    - windows

build:linux:
  extends: [.build]
  image: registry.gitlab.com/p34ch-main/docker-images/clang
  tags:
    - docker
