variables:
  GIT_STRATEGY: none
  PACKAGENAME: '$CI_PROJECT_NAME-$CI_COMMIT_TAG.zip'
  URL: '$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_PROJECT_NAME/$CI_COMMIT_TAG/'

stages:
  - build

.build:
  variables:
    GIT_STRATEGY: fetch
  stage: build
  interruptible: true
  script:
    - cmake --preset clang
    - cmake --build --preset clang --config Debug
    - cmake --build --preset clang --config Release
    - cd build/clang
    - ctest -V -C Debug
    - ctest -V -C Release

build:windows:
  extends: [.build]
  tags:
    - windows

build:linux:
  extends: [.build]
  image: registry.gitlab.com/p34ch-main/docker-images/clang
  tags:
    - docker

